### ISSUE TITLE
Problem: long-running jobs are killed on application upgrade

### ISSUE THREAD

**Issue by alPacino** [c-rack/quantum-elixir#14] opened 2015-08-13 01:14 UTC
When app is upgrading (using [exrm](https://github.com/bitwalker/exrm) for example) and some task id still processing some job the task is killed without waiting for completion.

I've dug into this problem but still have no solution. Even asked on stackoverflow.com ([Elixir Task - Graceful shutdown](http://stackoverflow.com/questions/31977215/elixir-task-graceful-shutdown)).

**Comment by c-rack** [comment] 2015-08-13 08:22
Do you think it is possible to send a PR with a minimal test that reproduces the problem? I saw your code on SO, but having our own test within the project might be better.

Also, this issue might be related to #8, where we need a similar behaviour (i.e. checking the status of tasks / waiting for tasks to finish).

**Comment by c-rack** [comment] 2015-10-30 18:44
@alPacino coming back to this issue, is it still relevant?
If yes, do you think you could provide a test case or a how-to-reproduce?
I could look into this issue over the weekend then.

**Comment by alPacino** [comment] 2015-10-30 21:57
@c-rack actually it is not quite difficult to reproduce this. Here are steps I used (now I have not checked this out yet):
- define some long-running (20 secs) task
- make a release (lat's say version is 0.0.1) using exrm and start the app from this release
- watch your log (tail -f log/yourapp.log)
- change the version (0.0.2) and build release for upgrade
- wait until task starts
- in another console upgrade your app like bin/yourapp upgrade 0.0.2
You should see in the log that your task was killed after 5000 ms even if you run Quantum tasks with "shutdown: 30000"
NOTE: copy your releases into some separate directory (not from yourapp/rel) and run app from it. Otherwise you will not be able to generate upgrade from release 0.0.1 to 0.0.2 because appup file is being deleted on upgrade.
Hope that's enough to reproduce

**Comment by c-rack** [comment] 2015-10-30 22:00
Thanks! I'll give it a try.

**Comment by chenxsan** [comment] 2017-01-17 08:46
Any update?

**Comment by maennchen** [comment] 2017-01-22 21:51
@alPacino I tried to put those conditions into a test and can't get it to fail. Do you have any suggestions?
https://github.com/jshmrtn/quantum-elixir/blob/feature/14_hot_code_reload/test/quantum_hot_code_reload_test.exs

**Comment by maennchen** [comment] 2017-01-24 11:23
@alPacino Does this look like your error?

```bash
mix test
.......................................
11:22:30.578 [info]  Application quantum exited: :stopped
.
11:22:31.112 [info]  Application quantum exited: :stopped

11:22:37.023 [info]  Application quantum exited: :stopped

11:22:37.023 [warn]  Job 'test_job' not started due to duplicate job name


  1) test do not crash jobs while hot code reload (QuantumHotCodeReloadTest)
     test/quantum_hot_code_reload_test.exs:59
     ** (exit) exited in: :sys.change_code(#PID<0.348.0>, TestModule, "1", [:hello])
         ** (EXIT) time out
     stacktrace:
       (stdlib) sys.erl:303: :sys.send_system_msg/2
       test/quantum_hot_code_reload_test.exs:80: (test)

..........

Finished in 9.3 seconds
51 tests, 1 failure

Randomized with seed 669514
```

**Comment by maennchen** [comment] 2017-01-31 21:41
@alPacino Closing this issue because we can't reproduce the issue and lack of participation. Reopen the issue when needed.

**Closed by maennchen** 2017-01-31 21:41 UTC
Labels: bug, help wanted
