### ISSUE TITLE
Problem: multi scheduling cron-like config with exrm

### ISSUE THREAD

**Issue by alPacino** [c-rack/quantum-elixir#15] opened 2015-08-13 01:52 UTC
Cron-like config works fine with [exrm](https://github.com/bitwalker/exrm) when there is only one scheduled job. Ex.:

```
config :quantum, cron: [
  "* * * * * MyApp.MyModule.my_method"
]
```

But if we define another one then release for your app can't be generated. Suggested solution is to define named scheduling like this:

```
config :quantum, cron: [
  news_letter: "* * * * * MyApp.NewsLetter.send",
  weekly_news_letter: "@weekly MyApp.NewsLetter.send",
  stats_gathering: "* * * * * MyApp.Stats.gather",
  daily_stats_gathering: "@daily MyApp.Stats.gather"
]
```
Or using another form:

```
config :quantum, cron: [
  news_letter: [
    schedule: "* * * * *",
    task: "MyApp.NewsLetter.send" # maybe {MyApp.NewsLetter, :send} will be supported too
  ] 
]
```

This also may be useful for pausing/deleting jobs using its names.

P.S. This doesn't break any existing config styles and behaviour. Just an option for compatibility with exrm.

**Comment by c-rack** [comment] 2015-08-13 08:14
I like the idea of named jobs. Given the two alternatives you describe (and I assume there might be more), we should find and then decide for the most practical one.

Could you please describe why `exrm` cannot generate a release if two or more jobs are defined? Is there an error message or any known limitations? I would like to understand the root cause of the problem first.

Thanks!

**Comment by alPacino** [comment] 2015-08-13 12:02
Sorry, it looks like config with multi scheduling works now. I forgot that I've recently updated exrm to the latest version but still was sure that it doesn't work properly (I use just one scheduled job). The problem was:
for config
```
config :quantum, cron: [
  "* * * * * MyApp.MyModule.perform1",
  "* * * * * MyApp.MyModule.perform2"
]
```

in the final config file rel/my_app/releases/0.0.1/my_app.conf (built with [conform](https://github.com/bitwalker/conform)) we have the following:
```
...
quantum.cron = "* * * * * MyApp.MyModule.perform1", "* * * * * MyApp.MyModule.perform2"
...
```

and exrm crashed while parsing this. Now it works fine but I'll check this out once again.

**Comment by c-rack** [comment] 2015-08-13 12:18
OK, thanks for the feedback. Please close this issue if confirmed.
We should open another issue for named jobs then.

**Comment by alPacino** [comment] 2015-08-14 00:22
Unfortunately, I can reproduce the issue. Release was built successfully, but I can't start my app, I got:
** (Protocol.UndefinedError) protocol Enumerable not implemented for \<content of my_app.conf\>

The problem is here:

```
...
# Provide documentation for quantum.cron here.
quantum.cron = "* * * * * MyApp.MyModule.perform1", "* * * * * MyApp.MyModule.perform2"
```

I've created simple application for that: [QuantumTest](https://github.com/alPacino/quantum-elixir-test)

**Comment by c-rack** [comment] 2015-08-14 07:42
Thanks! That is very helpful. :+1: 
Looks like a problem in `conform`: https://github.com/bitwalker/conform/issues/20.
Maybe I find a fix or workaround later today.

**Comment by bitwalker** [comment] 2015-08-17 18:57
This should be working fine in conform now (using master). I'll be pushing a new release to hex once I've vetted it a bit.

**Comment by alPacino** [comment] 2015-08-17 21:58
Confirmed! `conform`'s master branch works fine now (thanks to @bitwalker). So we can close this issue and open new one for named jobs.

**Comment by c-rack** [comment] 2015-08-18 07:59
@bitwalker thanks for fixing!
@alPacino thanks for confirmation!
So I close this issue.

**Closed by c-rack** 2015-08-18 07:59 UTC
Labels: enhancement
