### ISSUE TITLE
Node is not running error when using quantum with cluster

### ISSUE THREAD

**Issue by overture8** [c-rack/quantum-elixir#272] opened 2017-10-12 21:49 UTC
I'm getting an error in my logs after deploying quantum with multiple nodes. The error is getting thrown consistently from node 1, complaining that nodes 2 and 3 aren't running (but they are). If I connect a remote iex to node 1 and execute `Node.list`, I can see the other two nodes. Here's the error.

```elixir
warn: Node :"appserver@ip-10-0-1-212.eu-west-1.compute.internal" is not running. Job #Reference<0.1966477695.3470262273.172988> could not be executed.
```

My configuration is as follows:

```elixir
config :my_app, MyApp.Scheduler,
  global: true,
  jobs: [
    [schedule: "0 16 * * *",
     timezone: :utc,
     run_strategy: {Quantum.RunStrategy.Random, :cluster},
     task: {Core, :job1, []}],

    [schedule: "*/45 * * * *",
     timezone: :utc,
     run_strategy: {Quantum.RunStrategy.Random, :cluster},
     task: {Core, :job2, []}],

    [schedule: "*/45 * * * *",
     timezone: :utc,
     run_strategy: {Quantum.RunStrategy.Random, :cluster},
     task: {Core, :job3, []}]
  ]
```

I'm running quantum version 2.1.0. Any ideas where I'm going wrong?

**Comment by maennchen** [comment] 2017-10-12 22:27
@overture8 Can you check if there is a `TaskSupervisor` running on every node with the name `[YourSchedulerName].Task.Supervisor`?

(Hierarchy: `[YourSchedulerName]` => `Quantum.Supervisor` => `[YourSchedulerName].Task.Supervisor`)

**Comment by overture8** [comment] 2017-10-16 16:24
Sorry for the late reply. So, I did another deployment and I don't seem to be getting the error anymore. After deploying, I ran this on each host: `Process.whereis(MyApp.Scheduler.Task.Supervisor)` and got back a related PID. Not sure why it wasn't working originally.

**Comment by overture8** [comment] 2017-10-16 16:51
That said, and I'm not sure if this is related, sometimes when I deploy - jobs randomly don't run. Is there anyway to inspect what upcoming scheduled jobs there are? What steps would you take to diagnose an job that is falling to kick in at its scheduled time?

**Comment by maennchen** [comment] 2017-10-16 18:09
@overture8 Since the whole new system is based on GenStage, you could log all events, that are sent between the stages.

There is currently no logging or similar in place.

It could however be a great feature to log those events for debugging purposes in the future though.

**Comment by overture8** [comment] 2017-10-17 07:39
@maennchen Sounds like a good place to start - thanks for your help!

**Comment by overture8** [comment] 2017-10-18 08:08
Getting the same "Node is not running" errors in my logs again. It appeared again after doing another deployment - seems to happen randomly. I checked to see if the `MyApp.Scheduler.Task.Supervisor` was running and this time it wasn't - `Process.whereis(MyApp.Scheduler.Task.Supervisor)` returned `nil` - what would cause that?

Here is what my config looks like (if it is of any use):

```elixir
config :myapp, MyApp.Scheduler,
  global: true,
  jobs: [
    [schedule: "0 8 * * 1",
     timezone: :utc,
     run_strategy: {Quantum.RunStrategy.Random, :cluster},
     task: {Core, :job1, []}],

    [schedule: "*/30 * * * *",
     timezone: :utc,
     run_strategy: {Quantum.RunStrategy.Random, :cluster},
     task: {Core, :job2, []}],

    [schedule: "*/35 * * * *",
     timezone: :utc,
     run_strategy: {Quantum.RunStrategy.Random, :cluster},
     task: {Core, :job3, []}]
  ]
```

**Comment by maennchen** [comment] 2017-10-18 09:01
Hmmm.... Let me go over the supervision tree once again, maybe I'll spot an error.

**Comment by maennchen** [comment] 2017-10-18 09:07
@overture8 Do you see how far the Supervision Tree exists?

It should look something like this:

![screen shot 2017-10-18 at 09 06 52](https://user-images.githubusercontent.com/333918/31710169-c1252d0c-b3e3-11e7-95fe-a2500359b6de.png)

**Comment by maennchen** [comment] 2017-10-18 09:10
Or with `global` on:

![screen shot 2017-10-18 at 09 08 39](https://user-images.githubusercontent.com/333918/31710324-2998213c-b3e4-11e7-9d5c-e086898aa10d.png)

**Comment by overture8** [comment] 2017-10-18 10:40
Something I failed to notice is that `MyApp.Scheduler.Task.Supervisor` existing on 2 of the 3 servers. So, it seems it has just failed to start on one of the nodes. The supervision tree only goes as far as `MyApp.Scheduler` for the node where it is failing.

**Comment by overture8** [comment] 2017-11-01 12:09
Had this happen again on my last deployment. Two of the three nodes failed to start the `MyApp.Scheduler.Task.Supervisor` and the cron failed to run because of it. I had to do a `mix edeliver restart production` a few times before all three successfully returned a pid when running `Process.whereis(MyApp.Scheduler.Task.Supervisor)`.

**Comment by maennchen** [comment] 2017-11-07 05:14
@overture8 I tried to debug this with my machine (clustered, 3 nodes) but the process tree is always correct. I can't find any way to reproduce and therefore fix the issue.

**Comment by overture8** [comment] 2017-12-20 17:21
Possibly related. I noticed this in my server logs after deploying a minute ago:
```
Dec 20 05:07:53pm ip-10-0-0-1 info: global: Name conflict terminating {MyApp.Scheduler.ExecutorSupervisor, #PID<38798.3029.0>} 
Dec 20 05:07:53pm ip-10-0-0-1 info: global: Name conflict terminating {MyApp.Scheduler.TaskRegistry, #PID<38798.3025.0>} 
Dec 20 05:07:53pm ip-10-0-0-1 info: global: Name conflict terminating {MyApp.Scheduler.JobBroadcaster, #PID<38798.3026.0>} 

Dec 20 05:07:53pm ip-10-0-0-1 info: global: Name conflict terminating {MyApp.Scheduler.ExecutionBroadcaster, #PID<38798.3028.0>} 
```

**Comment by maennchen** [comment] 2017-12-21 07:57
@overture8 The name conflict always happens if you start two (or more) nodes and put them in the same cluster later. As soon as they are part of the same cluster, the worker names are duplicated and all except one worker of the same name will be instantly killed.

If you see this error, you either had a netsplit or you started the node before clustering it. This is something that I saw to happen using libs that join the cluster in runtime like [`libcluster`](https://github.com/bitwalker/libcluster).

Since the workers are literally killed and not stopped, there is no way to handle a conflict gracefully. (I don't know how to solve that problem without altering erlang otp)

What should never happen though, is that the cluster is in an invalid state after the conflict. I'm looking now how to solve this problem.

**Comment by maennchen** [comment] 2017-12-21 07:58
This seems to be a duplicate of #264.

**Closed by maennchen** 2017-12-21 07:58 UTC

**Comment by overture8** [comment] 2017-12-21 10:09
Thanks a lot for taking the time to look into this. I'll keep an eye on #264. 👍
