### ISSUE TITLE
Problem: jobs added in runtime do not execute

### ISSUE THREAD

**Issue by DFilipeS** [c-rack/quantum-elixir#269] opened 2017-09-26 13:42 UTC
Following the [Runtime Configuration](https://hexdocs.pm/quantum/runtime.html#content) in the documentation I added a new  task in runtime that should trigger every minute but nothing happens. No output, no errors, nothing.

```
MyApp.Scheduler.new_job() 
|> Quantum.Job.set_name(:ticker) 
|> Quantum.Job.set_schedule(~e[* * * * *]) 
|> Quantum.Job.set_task(fn -> IO.puts("PING") end) 
|> MyApp.Scheduler.add_job()
```

Starting a similar task in the config.exs file runs the task correctly. Any ideas?

PS: I just confirmed, this happens in the version 2.1.0 but in version **2.0.4 it works correctly**.

**Comment by maennchen** [comment] 2017-09-27 11:32
@DFilipeS I just tried to replicate the issue.

Steps to reproduce:
* `mix.new quantum_test --sup`
* Added deps to `mix.exs`
* Created `scheduler.ex` with the contents from `README.md`
* Added scheduler to `application.ex`
* Ran the code you provided.

I get a console output every minute. Can you try to reduce your problem / apply it to a new & clean app?

**Comment by maennchen** [comment] 2017-10-02 13:42
@DFilipeS Do you have any further information on how to reproduce the issue?

**Comment by kaiatgithub** [comment] 2017-11-06 17:03
I have a problem that may have the same cause. It seems that a job in the config can delay the execution of a job that is configured at runtime. Consider this configuration in version 2.1.2:
```
config :quantum_test, QuantumTest.Scheduler,
jobs: [
  [ name: :config_ticker,
    schedule: {:extended, "0 * * * * * *"},
    task: fn -> IO.puts "config_ticker " <> Timex.format!(Timex.now, "%T", :strftime) end
  ]
]
```
Then this function to add a job at runtime:
```
def add_runtime_job do
  Scheduler.new_job()
  |> Quantum.Job.set_name(:runtime_ticker)
  |> Quantum.Job.set_schedule(~e[* * * * * * *]e)
  |> Quantum.Job.set_task(fn -> 
    IO.puts "runtime_ticker " <> Timex.format!(Timex.now, "%T", :strftime) 
  end)
  |> Scheduler.add_job()
end
```

When I start the application with "iex -S mix" approx 20 secs before a full minute and call the above function approx 5 secs before a full minute, I get this output:
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
config_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:00
runtime_ticker 16:56:01
runtime_ticker 16:56:02
runtime_ticker 16:56:03
runtime_ticker 16:56:04
...

So somehow executions of the runtime_ticker get queued up until config_ticker is executed. The number of calls to "runtime_ticker" seems to depend on the start-time of the app. After config_ticker has been executed, the runtime_ticker executes as desired.

**Comment by maennchen** [comment] 2017-11-07 05:41
@kaiatgithub I found the error. It will be fixed with #281

**Comment by c-rack** [comment] 2017-11-07 06:09
Fixed by #281.

@DFilipeS @kaiatgithub could you please try again with current master?

**Closed by c-rack** 2017-11-07 06:09 UTC
Labels: bug

**Comment by kaiatgithub** [comment] 2017-11-07 15:16
Thank you @maennchen for the quick reply an fix. The runtime-job now executes immediately. 

However, there still is a dependency between the config-job and the runtime-job. The runtime-job can get executed many times when it is added. For example, when I start the app at second 10 and then add the job at second 15, it will get executed 5 times at second 15.

**Comment by maennchen** [comment] 2017-11-07 15:28
@kaiatgithub I can not reproduce that. My console output with your (slightly modified date output) example looks like this:

```
runtime_ticker 2017-11-07T15:26:51.001080
runtime_ticker 2017-11-07T15:26:52.001100
runtime_ticker 2017-11-07T15:26:53.001090
runtime_ticker 2017-11-07T15:26:54.001083
runtime_ticker 2017-11-07T15:26:55.001005
runtime_ticker 2017-11-07T15:26:56.000992
runtime_ticker 2017-11-07T15:26:57.001067
runtime_ticker 2017-11-07T15:26:58.001073
runtime_ticker 2017-11-07T15:26:59.001125
runtime_ticker 2017-11-07T15:27:00.001395
config_ticker 2017-11-07T15:27:00.001458
runtime_ticker 2017-11-07T15:27:01.001018
runtime_ticker 2017-11-07T15:27:02.000966
runtime_ticker 2017-11-07T15:27:03.001103
runtime_ticker 2017-11-07T15:27:04.001027
runtime_ticker 2017-11-07T15:27:05.001068
runtime_ticker 2017-11-07T15:27:06.001011
runtime_ticker 2017-11-07T15:27:07.001074
```

**Comment by kaiatgithub** [comment] 2017-11-08 14:56
I have been logging some state-information inside the execution_broadcaster and found the following:

1) When I add the runtime_ticker, the function "Scheduler.get_next_run_date" in "add_job_to_state" is provided with the start-time of the app (see init-function). So the next_run_date is the next second after the start-time of the app.

2) In "handle_info(:execute ...", the time variable is shifted one second forward, so that the  next_run_date is then up to 2 seconds after the start-time of the app.

I suggest that the next_run_date is always either the current time or a time in the future.

**Comment by maennchen** [comment] 2017-11-08 15:00
@kaiatgithub I can't just set the current time for the next run date. WIth the current solution if we have to much to execute in a second, the jobs will be queued and executed anyway. If I use the current time, we could skip some.

**Comment by kaiatgithub** [comment] 2017-11-08 15:13
@maennchen  Is it possible to do the check in the function add_job_to_state? Like this:
```elixir
min_run_date = max(time, NaiveDateTime.utc_now())
case Scheduler.get_next_run_date(schedule, DateLibrary.to_tz!(min_run_date, timezone)) do
  {:ok, date} ->
    add_to_state(state, DateLibrary.to_utc!(date, timezone), job)
```

**Comment by maennchen** [comment] 2017-11-08 16:02
@kaiatgithub I don't think so. Otherwise there could be skipped seconds if the execution takes too long.
