### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Lazarus404** [c-rack/quantum-elixir#211] opened 2017-07-06 11:57 UTC
So, we're using Quantum v1.9.2 but finding it's leaking processes.  We see a crash in our logs from Quantum and then

```
{{case_clause,
                   {error,
                    {{badmatch,
                      {error,
                       {‘EXIT’,
                        {system_limit,
                         [{erlang,spawn_link,
                           [proc_lib,init_p,
                            [quantum_tasks_sup,
                             [‘Elixir.Quantum.Supervisor’,<0.29364.75>],
```

Once Quantum has crashed, the process count drops from around 260k to 22k.

Thoughts?

**Comment by c-rack** [comment] 2017-07-06 12:00
Thanks for reporting this!

Would it be possible to provide a minimal app that reproduces this problem?

**Comment by maennchen** [comment] 2017-07-06 12:09
With an absolute minimum setup I can't reproduce the issue. The process count doesn't increase over time. Therefore we'll need the minimal app that @c-rack requested.

Used Code / Config:

```elixir
config :quantum, :my_app,
  cron: [
    {"* * * * *", &QuantumTest.heartbeat/0}
  ]
```

```elixir
defmodule QuantumTest do
  def heartbeat do
    IO.puts "heartbeat"
  end
end
```

**Comment by Lazarus404** [comment] 2017-07-06 12:28
So, what seems to be happening is;  Our cron just is set to very 
frequent.  One of those cron jobs crashes and, because the Quantum 
v1.9.2 dep has restarts set to permanent, it recreates the worker 
repetitively without the previous process cleaning up.  Eventually (and 
we're talking days), we hit our process ceiling.

We're investigating to find out why the processes aren't cleaning up and 
will notify when we figure it out.

Thanks

**Comment by maennchen** [comment] 2017-07-21 09:07
@Lazarus404 

I tried it with this config:

```elixir
use Mix.Config

config :quantum, :my_app,
  cron: [
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
    "@secondly": {QuantumGlobalTest, :heartbeat},
  ]
```

```elixir
defmodule QuantumGlobalTest do
  def heartbeat do
    raise "fail"
  end
end
```

The process count stays stable at 124 for the three hours I let it run.

**Comment by maennchen** [comment] 2017-07-21 09:13
(Same result with `1.9.2` and `2.0.0`)

**Comment by maennchen** [comment] 2017-08-06 12:14
I can find no errors in the library. Closing until new evidence is found.

**Closed by maennchen** 2017-08-06 12:14 UTC
Labels: bug, help wanted
