### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by craigp** [c-rack/quantum-elixir#261] opened 2017-09-04 06:03 UTC
Even if I set the config up exactly as described in the README/docs I get a `** (FunctionClauseError) no function clause matching in Quantum.Executor.execute/2` error.

My actual scheduler has nothing in it but the `use Quantum.Scheduler, otp_app: :myapp` line and the jobs config calls a function on a module with no arguments.

I've copied and pasted config from the docs just to be sure. The weird thing is that the schedule still seems to work. However, once I'd deployed to my staging environment with a schdule of `"* 6 * * *"` the scheduled job executed repeatedly for what looks like an hour.

The staging config included a timezone option: `timezone: "Australia/Melbourne"`. I see the same error as the above in my staging logs, adding or removing the timezone seems to have no effect on the error.

I tried all the various config options in the docs, including named jobs, all produced the same error on startup.

**Comment by craigp** [comment] 2017-09-04 06:36
I created a very simple sample app the reproduces the problem I'm seeing: https://github.com/craigp/quantum_test. 

Scheduler seems to work but it produces this error on startup:

```
08:34:11.344 [error] Task #PID<0.161.0> started from QuantumTest.Scheduler.Runner terminating
** (FunctionClauseError) no function clause matching in Quantum.Executor.execute/2
    (quantum) lib/quantum/executor.ex:23: Quantum.Executor.execute({~e[* * * * * *], {QuantumTest.Pinger, :ping, []}, :utc}, %{jobs: [nil: %Quantum.Job{name: nil, overlap: true, pids: [], run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[* * * * * *], state: :active, task: {QuantumTest.Pinger, :ping, []}, timezone: :utc}], opts: [jobs: [nil: %Quantum.Job{name: nil, overlap: true, pids: [], run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[* * * * * *], state: :active, task: {QuantumTest.Pinger, :ping, []}, timezone: :utc}], task_supervisor: QuantumTest.Scheduler.Task.Supervisor, runner: QuantumTest.Scheduler.Runner, global: false, cron: [], timeout: 5000, schedule: nil, overlap: true, timezone: :utc, run_strategy: {Quantum.RunStrategy.Random, :cluster}, name: QuantumTest.Scheduler, otp_app: :quantum_test, quantum: QuantumTest.Scheduler]})
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &Quantum.Executor.execute/2
    Args: [{~e[* * * * * *], {QuantumTest.Pinger, :ping, []}, :utc}, %{jobs: [nil: %Quantum.Job{name: nil, overlap: true, pids: [], run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[* * * * * *], state: :active, task: {QuantumTest.Pinger, :ping, []}, timezone: :utc}], opts: [jobs: [nil: %Quantum.Job{name: nil, overlap: true, pids: [], run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[* * * * * *], state: :active, task: {QuantumTest.Pinger, :ping, []}, timezone: :utc}], task_supervisor: QuantumTest.Scheduler.Task.Supervisor, runner: QuantumTest.Scheduler.Runner, global: false, cron: [], timeout: 5000, schedule: nil, overlap: true, timezone: :utc, run_strategy: {Quantum.RunStrategy.Random, :cluster}, name: QuantumTest.Scheduler, otp_app: :quantum_test, quantum: QuantumTest.Scheduler]}]
```

**Comment by maennchen** [comment] 2017-09-04 07:47
Thanks for the report.

This is a duplicate of #257. The release `v2.0.4` containing the fix will be released in ~ 5 minutes.

**Closed by maennchen** 2017-09-04 07:47 UTC
Labels: bug

**Comment by craigp** [comment] 2017-09-04 08:02
Awesome, thanks
